 9:29:53|     0.0030|        LOG|  INFO| Log started at Sun Sep  1 09:29:53 2019
 9:29:53|     0.0120|       MAIN|  OKAY| Initialised: ehook
 9:29:56|     3.3198|       MAIN|  OKAY| Initialised: ajax.ajax
 9:29:56|     3.3238|       MAIN|  OKAY| Initialised: json
 9:30: 8|    14.9021|       AJAX|  DEBG| Creating POST request with form:
 9:30: 8|    14.9061|       AJAX|  DEBG|  u           : belivipro9x99
 9:30: 8|    14.9081|       AJAX|  DEBG|  p           : belikhun
 9:30: 8|    14.9111|       AJAX|  INFO| Starting request: http://localhost/api/login
 9:30:12|    18.9794|      EHOOK|  EXCP| File Traceback:
 9:30:12|    18.9832|      EHOOK|  DEBG|  File                        main.py, line   25, in <module>
 9:30:12|    18.9852|      EHOOK|  DEBG|  File                        ajax.py, line   31, in ajax
 9:30:12|    18.9877|      EHOOK|  DEBG|  File                    sessions.py, line  581, in post
 9:30:12|    18.9907|      EHOOK|  DEBG|  File                    sessions.py, line  533, in request
 9:30:12|    18.9926|      EHOOK|  DEBG|  File                    sessions.py, line  646, in send
 9:30:12|    18.9946|      EHOOK|  DEBG|  File                    adapters.py, line  516, in send
 9:30:12|    18.9966|      EHOOK|  EXCP| ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03765890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
 9:30:12|    19.0016|        LOG|  INFO| Log ended.
